In [ ]:
import numpy as np
from numpy.random import randn

In [ ]:
N,Din, H, Dout = 64, 1000, 100, 10
x, y = randn(N,Din),randn(N,Dout)
w1, w2 = randn(Din, H), randn(H,Dout)

In [ ]:
def signed_sqr(x):
  return(x*x*x/abs(x))




In [ ]:
x.dot(w1)[0]

array([ -47.36126519,   48.98599103,   63.26597756,   88.47452853,
        -37.49296386,  -18.00151259,   -5.93691603,   -5.94631137,
        -12.60044935,  -28.95394403,   40.99854981,  -18.45786817,
          6.95642506,  -11.80746403,   31.27169098,  -28.02426019,
         64.11138667,   72.38874432,   -6.56186395,    6.93741082,
         22.90443279,  -20.18802124,  -28.83620648,  -12.78054542,
         14.18843201,   36.65611224,  -86.63526143,   49.65419648,
         17.37935206,   30.73448217,  -11.66943247,  -32.34301704,
          2.73584674,  -43.26938625,   21.48628834,   71.34602994,
        -42.29170956,   18.73769723,   62.26621868,  -17.5369625 ,
          7.85210821,  -51.6301509 ,   11.28385518,    7.59418431,
        -48.74094402,  -10.00633925,   -5.53049966,   -6.0897883 ,
         -6.90773152,   22.17590846,   -4.05619896,  -21.07629326,
          6.20886139,   -5.91267472,  -43.53573372,   25.07336167,
         29.29286428,  -37.73128135,    8.10161365,  -24.01331

In [ ]:
from sklearn.preprocessing import normalize



In [ ]:

#normalize rows of matrix
#normalize(x, axis=1, norm='l1')
n =normalize(signed_sqr(x.dot(w1)), axis=1, norm='l2')
n[2]

array([ 2.00847940e-01, -8.53476305e-03, -1.97644253e-02,  2.17571495e-02,
        6.21434133e-02,  6.73605933e-03,  1.26082788e-02, -2.54285697e-02,
       -6.83272616e-02,  4.81224162e-04,  1.98864742e-02,  3.27534494e-02,
       -4.01577292e-02,  7.63685210e-04, -1.84009188e-02, -2.58362853e-02,
        6.25123562e-03, -1.47136304e-01,  5.69319552e-03, -4.33821464e-02,
        1.42024852e-01, -2.97074293e-02, -4.77353886e-02,  1.51898894e-01,
       -9.75221224e-03, -2.75835367e-01,  4.61207812e-02,  8.22822347e-02,
       -7.92992789e-02,  3.58120464e-01,  4.35138433e-02,  8.97035006e-02,
       -2.08331159e-02,  6.63402422e-03, -2.02138576e-01, -3.25282699e-02,
       -6.93228865e-03, -1.47165895e-02,  3.14753355e-01, -1.46253585e-01,
        7.23695106e-02,  5.24956345e-02, -1.59702848e-01, -2.21401559e-02,
       -1.42320713e-01,  1.42665306e-02,  8.26943991e-03, -1.71386986e-02,
        1.41254823e-01, -1.06753083e-02,  3.19688855e-03,  3.28530157e-07,
        1.72620000e-01, -

In [ ]:
signed_sqr(x.dot(w1))[0].mean()

153.00982037766377

In [ ]:
for t in range(10000):
  h = 1.0/(1.0 + np.exp(-x.dot(w1)))
  #h = normalize(signed_sqr(x.dot(w1)), axis=1, norm='l2')
  y_pred =h.dot(w2)
  loss = np.square(y_pred - y).sum()
  dy_pred =2.0*(y_pred-y)
  dw2 = h.T.dot(dy_pred)
  dh = dy_pred.dot(w2.T)
  dw1 = x.T.dot(dh*h*(1-h))
  #dw1 = 2*x.T.dot(h*dh)

  w1 -= 1e-4 *dw1
  w2 -= 1e-4*dw2
  print(loss)

In [ ]:
dw1.shape

(1000, 64)

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame(zip(y,y_pred), columns= ['y','y_pred'])

y  \
0   [-0.33073891028354435, 0.7155351798785597, -2....   
1   [1.1267334317370203, -1.1599202154428296, 0.53...   
2   [-0.26527823296163067, -0.9429525137061291, -0...   
3   [0.2911898028231453, -0.6273023485799989, -0.6...   
4   [0.268248019935079, -0.9050363184172328, -1.30...   
..                                                ...   
59  [0.2163792857865177, -0.12658559921165186, 0.4...   
60  [-0.19702963074023336, 1.4514939513024814, -0....   
61  [-0.5012376680866277, -0.9483013958648556, 0.6...   
62  [-0.6602035512531346, 1.0417309656456308, -0.2...   
63  [1.1149141426497293, -0.9564061086205315, 0.59...   

                                               y_pred  
0   [-0.3302166819706809, 0.7156467934435811, -2.3...  
1   [1.1267385929088671, -1.1598153622254663, 0.53...  
2   [-0.26468149643504846, -0.9424658600521651, -0...  
3   [0.2911821315209824, -0.6276138535711806, -0.6...  
4   [0.2680126274715863, -0.9046996225771421, -1.3...  
..                                                ...  
59  [0.2161354202706101, -0.1265216101359642, 0.40...  
60  [-0.19778528571523757, 1.4499615281929592, -0....  
61  [-0.5015278835345556, -0.9487106052710684, 0.6...  
62  [-0.660758776212062, 1.0419356773467487, -0.22...  
63  [1.1152792141930092, -0.9556515203882812, 0.59...  

[64 rows x 2 columns]

In [ ]:
x[0]

In [ ]:
import numpy as np

# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

# Create random input and output data
x = np.random.randn(N, D_in)
y = np.random.randn(N, D_out)

# Randomly initialize weights
w1 = np.random.randn(D_in, H)
w2 = np.random.randn(H, D_out)


In [ ]:

learning_rate = 1e-6
for t in range(500):
    # Forward pass: compute predicted y
    h = x.dot(w1)
    h_relu = np.maximum(h, 0)
    y_pred = h_relu.dot(w2)

    # Compute and print loss
    loss = np.square(y_pred - y).sum()
    print(t, loss)

    # Backprop to compute gradients of w1 and w2 with respect to loss
    grad_y_pred = 2.0 * (y_pred - y)
    grad_w2 = h_relu.T.dot(grad_y_pred)
    grad_h_relu = grad_y_pred.dot(w2.T)
    grad_h = grad_h_relu.copy()
    grad_h[h < 0] = 0
    grad_w1 = x.T.dot(grad_h)

    # Update weights
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2

0 22719821.567574877
1 16931598.38211871
2 14466948.697146151
3 13175698.684341384
4 12140597.299954174
5 10809095.812959444
6 9174555.818869352
7 7323700.759075505
8 5584379.545706294
9 4083632.1661889995
10 2931603.5987317674
11 2086339.591811553
12 1499187.9694555355
13 1095246.6445450902
14 820996.1821225208
15 632222.216901527
16 500735.2046128738
17 406745.1206440686
18 337751.93487256597
19 285557.3131992894
20 244930.59808956593
21 212450.14068781806
22 185910.4771558227
23 163820.73892514087
24 145152.76662703976
25 129192.70711396211
26 115433.83146552095
27 103455.9560082563
28 92974.27573171142
29 83741.33810204302
30 75581.95603345064
31 68354.53246313884
32 61922.78061479013
33 56182.95460221199
34 51053.821755204175
35 46456.68176145759
36 42327.65051657241
37 38614.94427255784
38 35271.321624135366
39 32253.385271402487
40 29525.14488638803
41 27055.48568872541
42 24817.515334923573
43 22785.43645682346
44 20938.404996267258
45 19259.15965722697
46 17730.217068985414
47

In [ ]:
#leaky_relu
learning_rate = 1e-6
for t in range(500):
    # Forward pass: compute predicted y
    h = x.dot(w1)
    h_relu = np.maximum(h, 0.01*h)
    y_pred = h_relu.dot(w2)

    # Compute and print loss
    loss = np.square(y_pred - y).sum()
    print(t, loss)

    # Backprop to compute gradients of w1 and w2 with respect to loss
    grad_y_pred = 2.0 * (y_pred - y)
    grad_w2 = h_relu.T.dot(grad_y_pred)
    grad_h_relu = grad_y_pred.dot(w2.T)
    grad_h = grad_h_relu.copy()
    grad_h[h < 0] = grad_h[h < 0]*0.01
    grad_w1 = x.T.dot(grad_h)

    # Update weights
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2

0 25423271.93157734
1 17954450.881818667
2 14292931.237315912
3 12115047.518585725
4 10455537.776754454
5 8955925.98975499
6 7483364.401989578
7 6089744.163110247
8 4820556.058901381
9 3746882.384548058
10 2873233.5525682885
11 2196172.494049416
12 1682145.6449578549
13 1300031.2213764114
14 1016368.7104458963
15 806569.0776838589
16 649957.65240036
17 532057.9346887695
18 442009.6494939128
19 372297.080648814
20 317463.5551411641
21 273654.4542235808
22 238079.0054362399
23 208735.20936392737
24 184233.6977237714
25 163529.45349195047
26 145852.10114249756
27 130623.18431458442
28 117401.38807355921
29 105842.0145435245
30 95674.33575617314
31 86695.73919619175
32 78748.36440796008
33 71676.76488101337
34 65363.91388839415
35 59702.589874398866
36 54619.961560235344
37 50051.936492200635
38 45933.92041281995
39 42211.41781135998
40 38840.22835251667
41 35787.52787727414
42 33013.45411205914
43 30489.733623964246
44 28190.54503215336
45 26092.959020729595
46 24176.33542186497
47 22423.

In [ ]:
    h = x.dot(w1)
    #h_relu = np.maximum(h, 0.01*h)
    h_relu = np.square(np.maximum(h,0))
    h_relu = h_relu - np.square(np.maximum(-h,0))
    h_relu

array([[-1.67446444e+02, -7.59450044e+02,  5.76042587e+02, ...,
        -3.09328735e+03,  6.16079999e+01,  2.79465387e+01],
       [-1.46303083e+03, -9.53087528e+02,  1.72464880e+03, ...,
         9.54762158e+00,  1.54048907e+03,  5.85446745e+00],
       [-3.00069374e-01,  5.45272691e+02,  2.14421581e+03, ...,
         1.02522657e+03, -4.80750098e+02,  4.73960594e+02],
       ...,
       [ 3.62047325e+03,  3.59954418e+01, -3.56894716e+00, ...,
         7.10083872e+03, -2.90842432e+03, -1.22305123e+01],
       [ 3.42605109e+01, -6.67110181e+02, -1.19330173e+02, ...,
        -5.48511688e+00,  1.01034209e+03, -1.01606855e+03],
       [-2.08151161e+02,  3.10072799e+00,  1.87533240e+03, ...,
        -2.91576989e+00, -3.12827158e+02,  3.54096306e+01]])